# Generated by Django 6.0.5 on 2026-06-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_feedback_subject_alter_feedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default='Другое', max_length=150, verbose_name='Тема обращения'),
        ),
    ]
